title: MagneticHub.fr
description: Le blog dédié aux microservices et aux revenus passifs en ligne.
baseurl: "/MagneticHub.fr" # si tu es sur GitHub Pages dans un repo nommé MagneticHub.fr
url: "https://yayabed.github.io"
theme: minima

# Activer la prise en compte de tous les fichiers .md dans articles/
collections:
  articles:
    output: true
    permalink: /articles/:name/

# Inclure le dossier d'articles dans le build
include:
  - articles
