# Configuration de base
title: "MagneticHub.fr"
description: "Le blog dédié aux microservices et aux revenus passifs en ligne."
url: "https://yayabed.github.io"
baseurl: "/MagneticHub.fr"

# Structure du site
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Conversion des articles en posts
include:
  - _posts

# Traiter les fichiers dans /articles comme des posts
defaults:
  - scope:
      path: "articles"
      type: "posts"
    values:
      layout: "post"
      author: "YayaBed"
