title: MagneticHub.fr
description: Le blog dédié aux microservices et aux revenus passifs en ligne.
baseurl: ""  # Doit être vide pour les pages GitHub
url: "https://yayabed.github.io"  # L'URL de ton site
permalink: /articles/:title/  # Permet de lier les articles sans extension .md
