title: MagneticHub.fr
description: Bons plans puissants pour booster ta vie!
baseurl: ""  # Ne pas mettre de valeur ici, pour GitHub Pages
url: "https://yayabed.github.io"  # Ton URL GitHub Pages
permalink: /articles/:title/  # Pour que chaque article ait une URL propre
