# Configuration de base
title: "MagneticHub.fr"
description: "Le blog dédié aux microservices et aux revenus passifs en ligne."
url: "https://yayabed.github.io"  # L'URL de ton site
baseurl: ""  # Laisser vide pour un site GitHub Pages

# Permaliens
permalink: /articles/:title/  # Permet des URLs propres sans extension .md

# Structure du site
theme: jekyll-theme-cayman  # Tu peux changer de thème ici, ou en choisir un autre

# Configuration des articles
collections:
  articles:
    output: true
    permalink: /articles/:name/  # Structure des URLs des articles

# Paramètres de navigation
header_pages:
  - index.md
  - about.md

# Exemple de configuration de pagination (si tu as beaucoup d'articles)
paginate: 5  # Nombre d'articles par page

# SEO & social
social:
  twitter: "@YayaBed"  # Ton compte Twitter
  facebook: "https://www.facebook.com/YayaBed"  # Ton Facebook, si tu en as un

# Variables personnalisées
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "YayaBed"

# Configurations supplémentaires pour les plugins (facultatif)
plugins:
  - jekyll-feed  # Permet la génération d'un flux RSS
  - jekyll-seo-tag  # Améliore le SEO du site

# Options de sécurité et autres
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
