name: Update Index

on:
  push:
    paths:
      - 'articles/*.md'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Générer la liste des articles
        run: |
          echo "---" > index.md
          echo "title: Bienvenue sur MagneticHub.fr" >> index.md
          echo "layout: default" >> index.md
          echo "---" >> index.md
          echo "" >> index.md
          echo "# Bienvenue !" >> index.md
          echo "" >> index.md
          echo "Découvrez nos derniers articles :" >> index.md
          echo "" >> index.md

          for file in $(ls articles/*.md | sort); do
            title=$(grep -m 1 '^#' "$file" | sed 's/^# //')
            echo "- [$title]($file)" >> index.md
          done

      - name: Commit et push du nouveau index.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.md
          git commit -m "🔄 Mise à jour automatique de l’index"
          git push
